= Ferienhaus Vermietung

Dies ist die Lösung, die wir im Rahmen des Softwaretechnologie-Projekts an der TU Dresden entwickelt haben.

== Die Aufgabenstellung lautete wie folgt:

Gewünscht ist ein Webportal, was sich mit der Vermietung von Ferienhäusern im Raum in und um Dresden beschäftigen soll.
Es soll die Möglichkeit geboten werden, sich Ferienhäuser anzuschauen nach erfolgreicher Registrierung für einen bestimmten Zeitraum zu mieten. Das Haus wird dabei durch den Ort, eine Beschreibung, ein paar Bilder und dem Vermieter repräsentiert. Benutzer können dabei das Haus für einen bestimmten Zeitraum (Minimum/Maximum kann der jeweilige Vermieter festlegen) für sich reservieren oder buchen, sofern dieses noch zur gewünschten Zeit frei ist. Beginnt der Urlaub bereits in einem Monat oder weniger, ist keine Reservierung mehr möglich, sondern nur noch die Buchung. Bei einer Buchung fällt eine Anzahlung an, die sich auf ca. 10% der Gesamtkosten des Urlaubs beläuft. Diese muss er dem Vermieter fristgerecht (innerhalb von 7 Werktagen vor Urlaubsbeginn) überweisen, der dann die Buchung bestätigt. Ansonsten verfällt die Reservierung und wird wieder frei. Weiterhin ist vorgesehen, dass der einmal gebuchte Urlaub storniert werden kann. Bis zu einer gewissen Frist, einige Tage vor Urlaubsbeginn, soll das kostenfrei sein, während nach Ablauf dieser Frist die Anzahlung vom Vermieter einbehalten werden kann.

Es sind natürlich auch Vermieter vorhanden, die sich selbst aber nicht registrieren dürfen, sondern vom Administrator erstellt werden. Nach erfolgreichem Einloggen eines Vermieters hat dieser die Möglichkeit, seine Häuser zu verwalten, was im Wesentlichen bedeutet, neue Häuser im System einzutragen (die dann von anderen Nutzern eingesehen werden können), bestehende Häuser zu ändern oder zu löschen. Weiterhin muss er eine umfangreiche Übersicht über seine Häuser haben. Das beinhaltet eine Miethistorie, welche anzeigt, wer wann wie lange in dem Haus gelebt hat, eine Übersicht über aktuelle Buchungen und Reservierungen und eine Liste von Events. Der Vermieter hat somit die Möglichkeit, Buchungen und Reservierungen zu bestätigen oder zu verwerfen (wobei darauf zu achten ist, was passiert, wenn eine schon bezahlte Buchung rückgängig gemacht werden muss), Events zu bestätigen oder zu löschen und die Hausdetails zu verändern.

Weiterhin soll das Portal mit einer bereits angedeuteten Eventfirma zusammenarbeiten, die sich ebenfalls in und um Dresden engagiert. Eventmitarbeiter haben daher ebenfalls einen Zugang zu dem System. Diese können nach erfolgreichem Einloggen Events erstellen, verändern oder löschen. Dabei unterscheidet man große einmalige Events, für die eine Reservierung nötig ist, und kleinere wöchentliche stattfindende Events, die kostenfrei besuchbar sind. Größere Events müssen beim Buchen des Urlaubes mit zu gebucht werden, was es nötig macht, dass diese Events an ein oder mehrere Häuser gebunden sind. Natürlich kommen nur jene Häuser in Frage, die relativ nah zu den Veranstaltungsort des Events sind. Ein Event wird durch den Namen, den Ort, die Zeit, in der es stattfindet, und den Preis (ggf. kostenlos) beschrieben. Wenn ein größeres Event abgebrochen wird, müssen den Urlaubern, die gebucht haben auch ihre Kosten zurückerstattet werden. Bevor Events aber an Häuser gebunden werden und somit den Benutzern sichtbar werden, muss das vom jeweiligen Vermieter bestätigt werden. Kleinere Events bedürfen auch einer Bestätigung, müssen aber nicht gebucht werden und dienen somit den Benutzern lediglich als Hinweis, wie sie ihren Urlaub verleben können.
Als letztes wird ein Administratorzugang gebraucht, der das System verwalten soll. Im Wesentlichen bezieht sich das auf die Verwaltung von Mitgliedern, Löschen und Freischalten von Urlauberkonten und Erstellen und Löschen von Vermieter- und Eventmitgliederkonten.

== Details zur Lösung

Die Details zu unserer Lösung wurden im https://github.com/maxthure/swt18w20/blob/master/src/main/asciidoc/pflichtenheft.adoc[Pflichtenheft] festgehalten.
